apiVersion: v1
kind: Service
metadata:
  name: my-dotnet-app-service
spec:
  selector:
    app: my-dotnet-app  # Label selector matching your deployment
  ports:
    - protocol: TCP
      port: 80  # Port within the cluster
      targetPort: 80  # Port your application is listening on
  type: LoadBalancer

